server:
  listenaddr: "" # the address to bind on, leave empty to bind on all addresses
  port: 80 # the port for the http server
  ssl:
    enabled: false # if https should be enabled
  responseheaders: # response headers are added to every response (default: none)
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET,POST"
database: # see below
  dialect: ${GOTIFY_DATABASE_DIALECT}
  connection: ${GOTIFY_DATABASE_CONNECTION}
passstrength: 10 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: data/images # the directory for storing uploaded images
pluginsdir: data/plugins # the directory where plugin resides (leave empty to disable plugins)