on:
  push:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [ master ]
name: CI
jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate

    - name: Install front-end dependencies
      run: |
        npm install
        npm run dev

  test:
    name: Run project tests
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Run Testsuite
      run: vendor/bin/phpunit tests/
